### ISSUE TITLE
[k8sclusterreceiver] add k8s.container.status_last_terminated_reason metric

### ISSUE THREAD

**Issue by povilasv** [coralogix/opentelemetry-collector-contrib-old-fork#18641]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

I would like to get some container state metrics, about termination. One use case is to know whether the container was terminated due to OOM kill or application errorr.

Example happening in pod:
```
kubectl get pod X -o yaml

...
apiVersion: v1
kind: Pod
...
status:
  containerStatuses:
  - containerID: containerd://07ff7db2706d20ddd26c6257c1c1dbf176917f855c7feef0e05db88159b1584d
    image: image
    imageID:  imageId
    lastState:
      terminated:
        containerID: containerid
        exitCode: 2
        finishedAt: "2024-02-05T23:17:38Z"
        reason: Error
        startedAt: "2024-02-05T23:17:33Z"
```

Kube State Metrics has this modelled as this Prometheus metric:

>kube_pod_container_status_last_terminated_reason
> labels:
>container=<container-name>
> pod=<pod-name>
> namespace=<pod-namespace>
> reason=<last-terminated-reason>
> uid=<pod-uid>	

Ref: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md

So would be great to have a similar metric.

### Describe the solution you'd like

Not sure how to model it in otel correctly, but I'm thinking something like this:

```
  k8s.container.status_last_terminated_reason:
    enabled: false
    description: Last terminated reason of container. The unit is always 1.
    unit: ""
    attributes:
      - reason
    gauge:
      value_type: int
```
